# Generated by Django 4.0.2 on 2022-02-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_remove_devotee_linenos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devotee',
            old_name='address_address1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='devotee',
            old_name='address_address2',
            new_name='address_line2',
        ),
    ]
