# Generated by Django 4.0.2 on 2022-02-03 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accommodation', '0003_rename_address_address1_devotee_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room_number', models.CharField(blank=True, default='', max_length=70)),
                ('guesthouse_name', models.CharField(blank=True, choices=[('K', 'Kurangu Thottam'), ('A1', 'A Rooms'), ('A', 'Dispensary'), ('AA', 'Achalam Guest House'), ('R', 'Post Office Rooms'), ('M', 'Mourvi Guest House')], default='Kurangu Thottam', max_length=70)),
                ('room_type', models.CharField(blank=True, default='', max_length=70)),
                ('max_guest_in_room', models.CharField(blank=True, default='', max_length=70)),
                ('is_room_booked', models.CharField(blank=True, default='', max_length=25)),
                ('is_room_dirty', models.CharField(blank=True, default='', max_length=25)),
                ('house_keeping_instruction', models.CharField(blank=True, default='', max_length=50)),
                ('last_cleaned_date', models.CharField(blank=True, default='', max_length=15)),
                ('last_cleaned_by', models.CharField(blank=True, default='', max_length=50)),
                ('uopdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='devotee',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devotee', to=settings.AUTH_USER_MODEL),
        ),
    ]
