# Generated by Django 4.0.2 on 2022-02-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_room_devotee_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='house_keeping_instruction',
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_cleaned_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_cleaned_date',
        ),
        migrations.AlterField(
            model_name='room',
            name='is_room_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_room_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
