# Generated by Django 4.0.2 on 2022-02-04 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accommodation', '0006_alter_room_guesthouse_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devotee',
            old_name='uopdated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='uopdated',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='devotee',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_guest_in_room',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('likely_arrival', models.DateTimeField(auto_now_add=True)),
                ('likely_departure', models.DateTimeField(auto_now_add=True)),
                ('no_of_guests', models.IntegerField(blank=True, default=1)),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('is_request_approved', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('devotee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='devotee', to='accommodation.devotee')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
