# Generated by Django 4.0.2 on 2022-02-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_alter_room_guesthouse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='likely_arrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='likely_departure',
            field=models.DateTimeField(),
        ),
    ]
