# Generated by Django 4.0.2 on 2022-03-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0011_foreigndevotee_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='likely_checkout_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='likely_arrival',
            field=models.DateTimeField(),
        ),
    ]
